#include "bubbleSort.cpp"
#include "heapSort.cpp"
#include "mergeSort.cpp"
#include "shakerSort.cpp"
#include "flashSort.cpp"
#include "countingSort.cpp"
#include "insertionSort.cpp"
#include "radixSort.cpp"